### ISSUE TITLE
Auto-Scaling

### ISSUE THREAD

**Issue by khteh** [sanderploegsma/redis-cluster#18]
How does redis cluster handle auto-scaling in/out depends on load?

In the case of Kubernetes cluster, there is horizontal pod autoscaler. Does it work with redis cluster?

**Comment by sanderploegsma** [comment]
Unfortunately, autoscaling is not supported in this setup. You can add a HPA and it will create extra pods, but since the resharding process is manual, it won't have any effect as the new instances won't receive any keys.

As I stated in the README, I advise you to look for alternatives, since the setup in this repository is probably not that future-proof.
