### ISSUE TITLE
Docker image missing?

### ISSUE THREAD

**Issue by waltari2001** [sanderploegsma/redis-cluster#5]
Hi,

I cannot seem to find the docker image redis-cluster:v1.

**Comment by varunnayal** [comment]
It is to be buitl using dockerfile present in the repo!!!

**Comment by sanderploegsma** [comment]
Yes, I explicitly didn't publish the docker image because in general it's better to maintain your own images, unless it's either an official image or very well maintained (I don't consider this one well maintained).

By the way, Redis 5.0 has the `redis-trib` commands built into `redis-cli`, so no custom Docker image is needed anymore. I updated the repo to use the latest RC, feel free to check it out.
