### ISSUE TITLE
statefulset failover IP change

### ISSUE THREAD

**Issue by johnjavabean** [sanderploegsma/redis-cluster#6]
Hi there,

First thanks very much for contribute your solution for redis cluster which is super useful.

I just have a concern that statefulset only guarantees no change on domain of each node, however, the ip will still be changed. Will this break the cluster meet in cluster mode?

Thanks,
Jiabin

**Comment by riaan53** [comment]
Hi,

Redis cluster reconfigures the ip address automaticly when they detect
changes. The redis container thats down must just point to a valid redis
container when its back up. It will be best to run each statefulset on a
seperate host. If everything goes down you have a problem and you will have
to edit the nodes.conf file manually, but this should be rare.

Theres just one bug in redis that you need to manually hack around
https://github.com/antirez/redis/issues/4645

Also if you are using the latest redis version, the cluster commands are
now built into the redis-cli.

Hope this helps :)

Riaan Jacobs
riaan53@gmail.com

**Comment by sanderploegsma** [comment]
Thanks for the response @riaan53, since Redis is no longer part of my day job I kind of stopped focusing on it. Great point on the cluster commands being integrated in Redis 5.0, I updated the repo to reflect it.

Running the pods on separate nodes is always a good idea, if a master and its slave live on the same VM and that goes down, you lose one of the shards. Using `podAntiAffinity` to make sure pods are not co-located is an easy way to solve this issue.
